# @package _global_
answer_processor:
    _target_: ragfit.processing.answer_processors.regex.SimpleRegex
    pattern: "Answer"

metrics:
    - _target_: ragfit.evaluation.metrics.StringEM
    - _target_: ragfit.evaluation.metrics.NonEmpty

key_names:
    generated: text
    label: answers
    query: query

results_file:
generated_file: data/inference/baseline-hotpotqa-test-generated.jsonl
data_file: data/evaluation/facebook-kilt_tasks-hotpotqa-validation-raft-context-zeroshot.jsonl
limit:
feature:
use_wandb:
experiment:
wandb_entity:
