# @package _global_
answer_processor:
    _target_: ragfit.processing.answer_processors.regex.SimpleRegex
    pattern:

metrics:
    - _target_: ragfit.evaluation.metrics.StringEM

key_names:
    generated: text
    label: answers
    query: query

results_file:
generated_file: data/inference/baseline-triviaqa-test-generated.jsonl
data_file: data/evaluation/Tevatron-wikipedia-trivia-dev-raft-context-zeroshot.jsonl
limit:
use_wandb:
experiment:
wandb_entity:
