# @package _global_
model:
    _target_: ragfit.models.api.AzureLLM
    azure_endpoint: azure.endpoint.com
    azure_deployment: gpt-4o
    api_version: 2024-02-15-preview
    max_tokens: 500
    instruction: ragfit/processing/prompts/prompt_instructions/qa-short-no-rag.txt
    template: ragfit/processing/prompts/qa-no-rag.txt
    template_map:
        question: query
    extra_keys:
    examples:

data_file: data/evaluation/din0s-asqa-dev-shortans-raft-context-zeroshot.jsonl
generated_file: baseline-no-rag-asqa-test-gpt4-generated.jsonl
input_key: prompt
generation_key: output
target_key: answers
limit: 150
