# @package _global_
model:
    _target_: ragfit.models.api.AzureLLM
    azure_endpoint: azure.endpoint.com
    azure_deployment: gpt-4o
    api_version: 2024-02-15-preview
    max_tokens: 500
    instruction: ragfit/processing/prompts/prompt_instructions/qa-rephrase-N.txt
    template: ragfit/processing/prompts/qa-no-rag.txt
    template_map:
        question: query
    extra_keys:
        N: three
    examples:

data_file: data/evaluation/Tevatron-wikipedia-trivia-dev-raft-context-zeroshot.jsonl
generated_file: cotN-no-rag-triviaqa-test-gpt4-generated.jsonl
input_key: prompt
generation_key: output
target_key: answers
limit: 150
