name: asqa_baseline
cache: false
output_path: .
steps:
    - _target_: ragfit.processing.dataset_loaders.loaders.LocalLoader
      inputs: dev
      filename: asqa-dev.jsonl

    - _target_: ragfit.processing.local_steps.prompter.TextPrompter
      inputs: dev
      prompt_file: ragfit/processing/prompts/qa-short.txt
      output_key: prompt
      mapping:
            query: query

    - _target_: ragfoundry.processing.global_steps.output.OutputData
      inputs: dev
      prefix: asqa-baseline

